env:
  mysql:
    host: localhost:3306
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

server:
  port: 16004

logging:
  level:
    com.mimiter.payment:
      repository: info
  file:
    path: logs
    max-history: 30


spring:
  application:
    name: mimiter-payment
  datasource:
    url: jdbc:mysql://${env.mysql.host}/payment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: ${env.mysql.username}
    password: ${env.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 3MB
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${env.redis.host}
    port: ${env.redis.port}
    password: ${env.redis.password}
    database: 0
  cache:
    type: redis
  profiles:
    active: default

uid:
  timeBits: 30             # 时间位, 默认:30
  workerBits: 16           # 机器位, 默认:16
  seqBits: 7               # 序列号, 默认:7
  epochStr: "2019-02-20"   # 初始时间, 默认:"2019-02-20"
  enableBackward: true    # 是否容忍时钟回拨, 默认:true
  maxBackwardSeconds: 1    # 时钟回拨最长容忍时间（秒）, 默认:1
  CachedUidGenerator:     # CachedUidGenerator相关参数
    boostPower: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    #scheduleInterval: 60    # 默认:不配置此项, 即不使用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒

mimiter.payment:
  wx:
    merchantId:
    privateKey:
    merchantSerialNumber: 
    apiV3Key:
    notifyUrl: